create extension if not exists pgcrypto;

create table if not exists public.uploads (
  upload_id uuid primary key default gen_random_uuid(),
  report_date date not null,
  source_file text not null,
  file_hash text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_rows (
  id bigint generated by default as identity primary key,
  upload_id uuid not null references public.uploads(upload_id) on delete cascade,
  report_date date not null,
  source_file text not null,
  sku text,
  product text,
  size text,
  color text,
  qty numeric not null default 0,
  line_count numeric not null default 0,
  revenue numeric not null default 0,
  row_type text not null check (row_type in ('product','shipping','discount','total'))
);

create index if not exists sales_rows_report_date_idx on public.sales_rows(report_date);
create index if not exists sales_rows_product_idx on public.sales_rows(product);
create index if not exists sales_rows_color_idx on public.sales_rows(color);
create index if not exists sales_rows_size_idx on public.sales_rows(size);
create index if not exists sales_rows_row_type_idx on public.sales_rows(row_type);

alter table public.uploads enable row level security;
alter table public.sales_rows enable row level security;

-- No browser/client access is required. Next.js server routes use the service-role key.
-- Therefore we intentionally do NOT create anon select/insert policies.
